blog/urls.py
from django.conf.urls import url
from .views import post_list, post_detail, PostList

# urlpatterns = [
#     url(r'^$', post_list, name='blog_post_list'),
#     url(r'ˆ(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', 
#         post_detail, 
#         name='blog_post_detail'),
# ]

# This code uses class-based views. 
urlpatterns = [
    url(r'^$', PostList.as_view(), name='blog_post_list'),
    url(r'(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', 
        post_detail, 
        name='blog_post_detail'),
]

suorganizer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from organizer.views import tag_detail
from .views import redirect_root
from organizer import urls as organizer_urls
from blog import urls as blog_urls
from django.contrib.flatpages import urls as flatpages_urls
from user import urls as user_urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'suorganizer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', redirect_root),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(organizer_urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^user/', include(user_urls, app_name='user', namespace='dj-auth')),
]

user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from .views import DisableAccount

password_urls = [
    url(r'^change/$',
        auth_views.password_change,
        {'template_name': 'user/password_change_form.html',
        'post_change_redirect': reverse_lazy('dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name': 'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name': 'user/password_reset_form.html',
        'email_template_name': 'user/password_reset_email.txt',
        'subject_template_name': 'user/password_reset_subject.txt',
        'post_reset_redirect': reverse_lazy('dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name': 'user/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name': 'user/password_reset_confirm.html',
        'post_reset_redirect': reverse_lazy('dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'
        ),
    url(r'^reset/done/$',
        auth_views.password_reset_complete,
        {'template_name': 'user/password_reset_complete.html',
        'extra_context': {'form': AuthenticationForm}},
        name='pw_reset_complete'),
    url(r'^disable/$', DisableAccount.as_view(), name='disable'),

]

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='dj-auth:login', permanent=False)),
    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, 
        {'template_name': 'user/logged_out.html', 'extra_context': {'form': AuthenticationForm}},
        name='logout'),
    url(r'^password/', include(password_urls)),

]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth import get_user, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View

class DisableAccount(View):
    success_url = settings.LOGIN_REDIRECT_URL
    template_name = 'user/user_confirm_delete.html'

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def get(self, request):
        return TemplateResponse(request, self.template_name)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def post(self, request):
        user = get_user(request)
        user.set_unusable_password()
        user.is_active = False
        user.save()
        logout(request)
        return redirect(self.success_url)

user/templates/user/base_user.html
{% extends parent_template|default:"base.html" %}

user/templates/user/logged_out.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Logged out
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two eight columns">
        <p>You have successfully logged out.</p>
        {% include "user/login_form.html" with login_button='Log back in' %}
    </div>
</div>
    
{% endblock %}

user/templates/user/login.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super}} - Login    
{% endblock %}

{% block content %}
<div class="row">
    <div class="offset-by-two five columns">
        {% include "user/login_form.html" %}
    </div>
</div>
<div>
    <ul>
        <li><a href="{% url "dj-auth:pw_reset_start" %}">Forgotten password?</a></li>
    </ul>
</div>
    
{% endblock %}

user/templates/user/login_form.html
<form action="{% url "dj-auth:login" %}" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    {% if next %}
    <input type="hidden" name="next" value="{{ next }}">
    {% endif %}
    <button type="submit">{{ login_button|default:'Log in' }}</button>    
</form>

user/templates/user/password_change_done.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Change Password
{% endblock %}

{% block content %}
  <div class="row">
      <div class="offset-by-two eight columns">
        <p>Password successfully changed.</p>
          
      </div>
  </div>
    
{% endblock %}

user/templates/user/password_change_form.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
  <div class="row">
      <div class="offset-by-two eight columns">
        
    <form action="{% url "dj-auth:pw_change" %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Password</button>
    </form>
          
      </div>
  </div>
    
{% endblock %}

user/templates/user/password_reset_complete.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Password Reset Successful
{% endblock %}

{% block content %}
    <div>
        <div>
            <p>Your password has been reset.</p>
            <p>Log in below using your new password.</p>
            {% include "user/login_form.html" %}
        </div>
    </div>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
    <div>
        <div>
        {% if validlink %}
        <p>Enter a new password below.</p>
        <form action="{{ request.path }}" method="post">
            {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save new password.</button>
        </form>
        {% else %}
        <p>This reset link is no longer valid.</p>
        <p>Please request a new reset email 
        <a href="{% url "dj-auth:pw_reset_start" %}">here</a></p>
        {% endif %}
        </div>
    </div>
{% endblock %}

user/templates/user/password_reset_form.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Reset Password
{% endblock %}

{% block content %}
<div>
    <div>
        <div>
            <p>Reset your password by email.</p>
        </div>
    <form action="{% url "dj-auth:pw_reset_start" %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit">Send me reset instructions.</button>
        
    </form>
    </div>
</div>
{% endblock %}

user/templates/user/password_reset_sent.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Password Reset Sent
{% endblock %}

{% block content %}
    <div>
        <div>
            <p>Password reset email sent.</p>
            <p>Please check your inbox and spam box!</p>
        </div>
    </div>
{% endblock %}

user/templates/user/user_confirm_delete.html
{% extends "user/base_user.html" %}

{% block title %}
{{ block.super }} - Disable Account
{% endblock %}

{% block content %}
<div>
    <div>
        <p>Disable your account?</p>
        <p>This cannot be undone.</p>
        <form action="{% url "dj-auth:disable" %}" method="post">
            {% csrf_token %}
            <button type="submit">Disable Account</button>
        </form>
    </div>
</div>
    
{% endblock %}