blog/urls.py
from django.conf.urls import url
from .views import post_list, post_detail, PostList

# urlpatterns = [
#     url(r'^$', post_list, name='blog_post_list'),
#     url(r'ˆ(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', 
#         post_detail, 
#         name='blog_post_detail'),
# ]

# This code uses class-based views. 
urlpatterns = [
    url(r'^$', PostList.as_view(), name='blog_post_list'),
    url(r'(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', 
        post_detail, 
        name='blog_post_detail'),
]

organizer/urls.py
from django.conf.urls import url

from .views import tag_detail, startup_detail, tag_create, StartupList, TagList, TagCreate

urlpatterns = [
    url(r'^$', StartupList.as_view(), name='organizer_startup_list'),
    #url(r'^tag/create/$', tag_create, name='organizer_tag_create'),
    url(r'^tag/create/$', TagCreate.as_view(), name='organizer_tag_create'),
    #url(r'^startup/$', startup_list, name='organizer_startup_list'),
    url(r'ˆstartup/(?P<slug>[\w\-]+)/$', startup_detail, name='organizer_startup_detail'), 
    url(r'^tag/$', TagList.as_view(), name='organizer_tag_list'),
    url(r'^tag/(?P<slug>[\w\-]+)/$', tag_detail, name='organizer_tag_detail'),
]

suorganizer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from organizer.views import tag_detail
from .views import redirect_root
from organizer import urls as organizer_urls
from blog import urls as blog_urls
from django.contrib.flatpages import urls as flatpages_urls
from user import urls as user_urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'suorganizer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', redirect_root),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(organizer_urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^user/', include(user_urls, app_name='user', namespace='dj-auth')),
]

organizer/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config.')
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_tag_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField()
    description = models.TextField()
    founded_date = models.DateField()
    contact = models.EmailField()
    website = models.URLField()
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name

    def get_absolute_url(self): # Here reverse() is used with args, not kwargs. 
        return reverse('organizer_startup_detail', args=(self.slug,))

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'


class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup) # many to one relationship (many news links to one startup)

    def __str__(self):
        return "{} : {}".format(self.startup, self.title)

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Tag, NewsLink, Startup


class SlugCleanMixin():

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError('Slug may not be "create".')
        return new_slug


class TagForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__' # or ['name', 'slug']

    def clean_name(self):
        return self.cleaned_data['name'].lower()

    # def clean_slug(self):
    #     new_slug = (self.cleaned_data['slug'].lower())
    #     if new_slug == 'create':
    #         raise ValidationError('Slug may not be "create".')
    #     return new_slug


class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'


class StartupForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Startup
        fields = '__all__'

    # def clean_slug(self):
    #     new_slug = (self.cleaned_data['slug'].lower())
    #     if new_slug == 'create':
    #         raise ValidationError('Slug may not be "create".')
    #     return new_slug


class TagForm_2(forms.Form):
    name = forms.CharField(max_length=31)
    slug = forms.SlugField(max_length=31, help_text='A label for URL config.')

    def save(self):
        new_tag = Tag.objects.create(
            name = self.cleaned_data['name'],
            slug = self.cleaned_data['slug'])
        return new_tag

    def clean_name(self):
        return self.cleaned_data['name'].lower()

    def clean_slug(self):
        new_slug = (self.cleaned_data['slug'].lower())
        if new_slug == 'create':
            raise ValidationError('Slug may not be "create".')
        return new_slug

organizer/views.py
from django.http.response import HttpResponse, Http404
from .models import Tag, Startup
from django.template import Context, loader, RequestContext
from django.shortcuts import get_object_or_404, render_to_response, render 
from .forms import TagForm
from django.shortcuts import redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import View, CreateView, DeleteView, DetailView, ListView
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator


class TagList(View):
    page_qwarg = 'page'
    paginate_by = 5
    template_name = 'organizer/tag_list.html'

    def get(self, request):
        tags = Tag.objects.all()
        paginator = Paginator(tags, self.paginate_by)
        page_number = request.GET.get(self.page_qwarg)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        if page.has_previous():
            prev_url = "?{pkw}={n}".format(pkw=self.page_qwarg, n=page.previous_page_number())
        else:
            prev_url = None
        if page.has_next():
            next_url = "?{pkw}={n}".format(pkw=self.page_qwarg, n=page.next_page_number())
        else:
            next_url = None
        context = {
            'is_paginated': page.has_other_pages(),
            'next_page_url': next_url,
            'paginator': paginator,
            'previous_page_url': prev_url,
            'tag_list': page
        }
        return render(request, self.template_name, context)

class TagCreate(CreateView):
    form_class = TagForm
    model = Tag

    @method_decorator(login_required)
    @method_decorator(permission_required('organizer.add_tag', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


def tag_list_2(request): # homepage() is now tag_list()
    tag_list = Tag.objects.all()
    template = loader.get_template('organizer/tag_list.html')
    context = Context({'tag_list': tag_list})
    output = template.render(context)
    return HttpResponse(output)

# render_to_response() is used here to shorten the code.
def homepage_2(request):  
    return render_to_response('organizer/tag_list.html', {'tag_list': Tag.objects.all()})

# RequestContext() is used here instead of Context()
def homepage_3(request):
    tag_list = Tag.objects.all()
    template = loader.get_template('organizer/tag_list.html')
    context = RequestContext(request, {'tag_list': tag_list})
    output = template.render(context)
    return HttpResponse(output)

# render() is used here instead of render_to_response(). It automatically uses RequestContext()
def homepage_4(request):
    return render(request, 'organizer/tag_list.html', {'tag_list': Tag.objects.all()})

def tag_create(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            new_tag = form.save()
            return redirect(new_tag)
    else:
        form = TagForm()
    return render(request, 'organizer/tag_form.html', {'form': form})

def tag_detail(request, slug):
    try:                                         
        tag = Tag.objects.get(slug__iexact=slug)
    except Tag.DoesNotExist:
        raise Http404
    template = loader.get_template('organizer/tag_detail.html')
    context = Context({'tag': tag})
    return HttpResponse(template.render(context))

# get_object_or_404() and render_to_response() are used to shorten the code.
def tag_detail_2(request):  
    tag = get_object_or_404(Tag, slug__iexact=slug)
    return render_to_response('organizer/tag_detail.html', {'tag': tag})

# RequestContext() is used here instead of Context()
def tag_detail_3(request):
    tag = get_object_or_404(Tag, slug__iexact=slug)
    template = loader.get_template('organizer/tag_detail.html')
    context = RequestContext(request, {'tag': tag})
    return HttpResponse(template.render(context))

# render() is used here instead of render_to_response(). It automatically uses RequestContext()
def tag_detail_4(request):
    tag = get_object_or_404(Tag, slug__iexact=slug)
    return render(request, 'organizer/tag_detail.html', {'tag': tag})

class StartupList(View):
    page_qwarg = 'page'
    paginate_by = 5
    template_name = 'organizer/startup_list.html'

    def get(self, request):
        startups = Startup.objects.all()
        paginator = Paginator(startups, self.paginate_by)
        page_number = request.GET.get(self.page_qwarg)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        if page.has_previous():
            prev_url = "?{pkw}={n}".format(pkw=self.page_qwarg, n=page.previous_page_number())
        else:
            prev_url = None
        if page.has_next():
            next_url = "?{pkw}={n}".format(pkw=self.page_qwarg, n=page.next_page_number())
        else:
            next_url = None
        context = {
            'is_paginated': page.has_other_pages(),
            'next_page_url': next_url,
            'paginator': paginator,
            'previous_page_url': prev_url,
            'startup_list': page
        }
        return render(request, self.template_name, context)

def startup_list_2(request):
    return render(request, 'organizer/startup_list.html', {'startup_list': Startup.objects.all()})

def startup_detail(request, slug):
    startup = get_object_or_404(Startup, slug__iexact=slug)
    return render(request, 'organizer/startup_detail.html', {'startup': startup})


# def homepage(request):
#     tag_list = Tag.objects.all()
#     output = ", ".join([tag.name for tag in tag_list])
#     return HttpResponse(output)

# def homepage(request):
#  tag_list = Tag.objects.all()
#  html_output = "<html>\n"
#  html_output += "<head>\n"
#  html_output += " <title>"
#  html_output += "Don't Do This!</title>\n"
#  html_output += "</head>\n"
#  html_output += "<body>\n"
#  html_output += " <ul>\n"
#  for tag in tag_list:
#    html_output += " <li>"
#    html_output += tag.name.title()
#    html_output += "</li>\n"
#  html_output += " </ul>\n"
#  html_output += "</body>\n"
#  html_output += "</html>\n"
#  return HttpResponse(html_output)

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ startup.name|title }}
{% endblock %}

{% block content %}
<article>
    <h2>{{ startup.name }}</h2>
    <dl>
        <dt>Date Founded</dt>
        <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
        <dt>Website</dt>
        <dd>{{ startup.website|urlize }}</dd>
        <dt>Contact</dt>
        <dd>{{ startup.contact }}</dd>
        <dt>Tag{{ startup.tags.count|pluralize }}</dt>
        {% for tag in startup.tags.all %}
        <dd><a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
        </a></dd>
        {% endfor %}
    </dl>

    {{ startup.description|linebreaks }}

    {% if startup.newslink_set.all %}
    <section>
        <h3>Recent News</h3>
        <ul>
            {% for newslink in startup.newslink_set.all %}
            <li><a href="{{ newslink.link }}">{{ newslink.title|title }}</a></li>
            {% endfor %}
        </ul>
    </section>
    {% endif %}

    {% if startup.blog_post.all %}
    <section>
        <h3>Blog Post{{ startup.blog_posts.count|pluralize }}</h3>
        <ul>
            {% for post in startup.blog_posts.all %}
            <li><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a></li>
            {% endfor %}
        </ul>
    </section>
    {% endif %}

</article>

{% endblock %}

organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startups
{% endblock %}

{% block content %}
<h2>Startup List</h2>
<ul>
    {% for startup in startup_list %}
    <li><a href="{% url 'organizer_startup_detail' startup.slug %}">{{ startup.name }}</a></li>
    {% empty %}
    <li><em>No startups available!</em></li>
    {% endfor %}
</ul>

{% if is_paginated %}
    <div>
        {% if previous_page_url %}
                <a href="{{ previous_page_url }}">Previous</a>
        {% endif %}
        Page {{ startup_list.number }} of {{ paginator.num_pages }}
        {% if next_page_url %}
                <a href="{{ next_page_url }}">Next</a>
        {% endif %}
    </div>
{% endif %}

{% endblock %}

<!-- We have defined get_absolute_url() method on Startup model, so we can replace url template tag
with a template variable. Like so-
    <li><a href="{% url 'organizer_startup_detail' startup.slug %}">
    <li><a href="{{ startup.get_absolute_url }}">
 -->

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
{{ tag.name|title }}
{% endblock %}

{% block content %}
<h2> {{ tag.name|title}} </h2>
{% if tag.startup_set.all %}
<section>
    <h3>Startups</h3>
    <ul>
        {% for startup in tag.startup_set.all %}
        <li><a href="{{ startup.get_absolute_url }}">
            {{ startup.name }}
        </a></li>
        {% endfor %}
    </ul>
</section>
{% endif %}

<section>
    <h3>Blog Posts</h3>
    {% if tag.blog_posts.all %}
    <ul>
        {% for post in tag.blog_posts.all %}
        <li><a href="{{ post.get_absolute_url }}">
            {{ post.title|title }}
        </a></li>
        {% endfor %}
    </ul>
</section>
{% endif %}
{% if not tag.startup_set.all and not tag.blog_posts.all %}
<p>This tag is not related to any content.</p>
{% endif %}

{% endblock %}

organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% load bootstrap %}

{% block title %}
    {{ block.super }} - Create Tag
{% endblock %}

{% block content %}
<!--
<form action="{% url "organizer_tag_create" %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.name.errors }}
    <p><label for="id_name">Name:</label>{{ form.name }}</p>
    {{ form.slug.errors }}
    <p><label for="id_slug">Slug:</label>{{ form.slug }}
        <span class="helptext">{{ form.slug.help_text }}</span></p>
    <button type="submit">Create Tag</button>
</form>
-->
<form action="{% url "organizer_tag_create" %}" method="post">
    {% csrf_token %}
    {% comment "using a library/app/module to style your forms" %}
         {{ form|bootstrap }}   
    {% endcomment %}
    
    {{ form.as_p }}
    
    <button type="submit">Create Tag</button>
</form> 
{% endblock %}

organizer/templates/organizer/tag_form2.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Create Tag
{% endblock %}

{% block content %}

<form action="{% url "organizer_tag_create" %}" method="post">

    {% csrf_token %}
    
    {% if form.non_field_errors %}
        <ul class="custom_error_list">
            {% for error in form.non_field_errors %}
                <li><em>{{ error }}</em></li>
            {% endfor %}
        </ul>
    {% endif %}

    <p><label for="id_name">Name:</label>{{ form.name }}</p>
    {% if form.name.errors %}
        <ul class="custom_error_list">
            {% for error in form.name.errors %}
                <li><em>{{ error }}</em></li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if form.name.value %}
        <input type="text" name="name" id="id_name" maxlength="31" value="{{ form.name.value }}">
    {% else %}
        <input type="text" name="name" id="id_name" maxlength="31">
    {% endif %}

    <p><label for="id_slug">Slug:</label>{{ form.slug }}
        <span class="helptext">{{ form.slug.help_text }}</span></p>
        {% if form.slug.errors %}
            <ul class='custom_error_list'>
                {% for error in form.slug.errors %}
                <li><em>{{ error }}</em></li>
                {% endfor %}
            </ul>
        {% endif %}
    <button type="submit">Create Tag</button>
</form>    
{% endblock %}

organizer/templates/organizer/tag_form3.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
  <form action="{% url "organizer_tag_create" %}" method="post">
    {% csrf_token %}
<p>
<label for="id_name">Name:</label><input type="text" name="name" id="id_name" maxlength="31">
</p>
<p>
<label for="id_slug">Slug:</label><input type="text" name="slug" id="id_slug" maxlength="31">
<span class="help_text">A label for URL config.</span>
</p>
<button type="submit">Create Tag</button>      
  </form>    
{% endblock  %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
{{ block.super }} - Tag List
{% endblock %}

{% block content %}
<h2>Tag List</h2>
<ul>
    {% for tag in tag_list %}
    <li><a href="{% url 'organizer_tag_detail' tag.slug %}">
        {{ tag.name|title }}
    </a></li>
    {% endfor %}
</ul>

{% if is_paginated %}
    <div>
        {% if previous_page_url %}
                <a href="{{ previous_page_url }}">Previous</a>
        {% endif %}
        Page {{ tag_list.number }} of {{ paginator.num_pages }}
        {% if next_page_url %}
                <a href="{{ next_page_url }}">Next</a>
        {% endif %}
    </div>
{% endif %}

{% endblock %}

<!-- We have defined get_absolute_url() method on Tag model, so we can replace url template tag
with a template variable. Like so-
    <li><a href="{% url 'organizer_tag_detail' tag.slug %}">
    <li><a href="{{ tag.get_absolute_url }}">
 -->