blog/urls.py
from django.conf.urls import url
from .views import post_list, post_detail, PostList

# urlpatterns = [
#     url(r'^$', post_list, name='blog_post_list'),
#     url(r'ˆ(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', 
#         post_detail, 
#         name='blog_post_detail'),
# ]

# This code uses class-based views. 
urlpatterns = [
    url(r'^$', PostList.as_view(), name='blog_post_list'),
    url(r'(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', 
        post_detail, 
        name='blog_post_detail'),
]

suorganizer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from organizer.views import tag_detail
from .views import redirect_root
from organizer import urls as organizer_urls
from blog import urls as blog_urls
from django.contrib.flatpages import urls as flatpages_urls
from user import urls as user_urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'suorganizer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', redirect_root),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(organizer_urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^user/', include(user_urls, app_name='user', namespace='dj-auth')),
]

user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from .views import DisableAccount

password_urls = [
    url(r'^change/$',
        auth_views.password_change,
        {'template_name': 'user/password_change_form.html',
        'post_change_redirect': reverse_lazy('dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name': 'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name': 'user/password_reset_form.html',
        'email_template_name': 'user/password_reset_email.txt',
        'subject_template_name': 'user/password_reset_subject.txt',
        'post_reset_redirect': reverse_lazy('dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name': 'user/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name': 'user/password_reset_confirm.html',
        'post_reset_redirect': reverse_lazy('dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'
        ),
    url(r'^reset/done/$',
        auth_views.password_reset_complete,
        {'template_name': 'user/password_reset_complete.html',
        'extra_context': {'form': AuthenticationForm}},
        name='pw_reset_complete'),
    url(r'^disable/$', DisableAccount.as_view(), name='disable'),

]

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='dj-auth:login', permanent=False)),
    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, 
        {'template_name': 'user/logged_out.html', 'extra_context': {'form': AuthenticationForm}},
        name='logout'),
    url(r'^password/', include(password_urls)),

]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        Startup Organizer
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static "organizer/style.css" %}">
        {% block head %} 

        {% endblock %}

</head>
<body>
    <div class="container">
        <div class="status row">
            <div class="offset-by-eight four columns">
                <ul class="inline">
                    {% if user.is_authenticated %}
                    <li>
                    <a href="{% url "dj-auth:logout" %}?next={{ request.path }}">Log out</a>
                    </li>
                    {% else %}
                    <li>
                    <a href="{% url "dj-auth:login" %}?next={{ request.path }}">Log in</a>
                    </li>    
                    {% endif %}
                    
                </ul>
            </div>
        </div>
        <header>
            <img src=" {% static "site/logo.png" %} " alt="Site logo" >
            <h1>Startup Organizer</h1>
        </header>
        <nav class="nav">
        <ul>
            <li><a href="{% url 'blog_post_list' %}">Blog</a></li>
            <li><a href="{% url 'organizer_startup_list' %}">Startups</a></li>
            <li><a href="{% url 'organizer_tag_list' %}">Tags</a></li>
        </ul>
        </nav>
        <main class="main">
            {% block content %}
            This is default content.
            {% endblock %}
        </main>
    </div>

    <footer class="footer">
        <p>
            &copy;2015
            <a href="https://andrewsforge.com">
                Andrew Pinkham</a>
        </p>
    </footer>

</body>

</html>